name: jison2dart
version: 0.6.0
description: Generate Dart parsers using Jison (Bison in JavaScript)
homepage: https://github.com/rikulo/jison2dart

dependencies:

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: any
