name: jison2dart
version: 0.5.3
description: > 
  Generate Dart parsers using Jison based on Bison parser generator
homepage: https://github.com/rikulo/jison2dart

dependencies:

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  test: any